id: toy-sphere-de

objective:
  direction: minimize

parameters:
  x:
    type: real
    value: 0.1
    bounds: [-5.0, 5.0]

  y:
    type: real
    value: -0.2
    bounds: [-5.0, 5.0]

  n:
    type: int
    value: 5
    optimizable: false

  mode:
    type: categorical
    value: a
    optimizable: false

evaluator:
  command: ["{python}", "../../tests/toy_eval.py"]
  timeout_s: 60
  env:
    OMP_NUM_THREADS: "1"

optimizer:
  name: differential_evolution
  seed: 123
  max_evaluations: 1000
  batch_size: 100

  settings:
    mutation_factor: 0.8
    crossover_rate: 0.9
    max_generations: 10

context:
  note: "toy example using Differential Evolution"